package ui.dialogs;

import ui.formcomponents.DialogWithCreditsInterface;
import ui.formcomponents.DialogWithCatalogInterface;
import ui.sessions.ProducerSession;

public class ProducerFrame extends javax.swing.JFrame implements DialogWithCatalogInterface, DialogWithCreditsInterface {

    private ProducerSession session;
    
    /** Creates new form ProducerFrame */
    public ProducerFrame(ProducerSession session) {
        initComponents();
        this.session = session;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        catalogPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catalogTable = new javax.swing.JTable();
        catalogSearchPanel = new javax.swing.JPanel();
        catalogSearchLabel = new javax.swing.JLabel();
        catalogSearchField = new javax.swing.JTextField();
        catalogFieldComboBox = new javax.swing.JComboBox();
        catalogSearchOKButton = new javax.swing.JButton();
        publicationsPanel = new javax.swing.JPanel();
        publicationsSearchPanel = new javax.swing.JPanel();
        publicationsSearchLabel = new javax.swing.JLabel();
        publicationsSearchField = new javax.swing.JTextField();
        publicationsFieldComboBox = new javax.swing.JComboBox();
        publicationsSearchOKButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        publicationsTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        greetingsLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        publishButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        systemMenu = new javax.swing.JMenu();
        publishMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        changePasswordMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ui.dialogs.TrabalhoES1App.class).getContext().getResourceMap(ProducerFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        catalogPanel.setName("catalogPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        catalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Gênero", "Álbum", "Artista/Banda", "Popularidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catalogTable.setName("catalogTable"); // NOI18N
        catalogTable.setRowHeight(25);
        catalogTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(catalogTable);

        catalogSearchPanel.setName("catalogSearchPanel"); // NOI18N

        catalogSearchLabel.setFont(resourceMap.getFont("catalogSearchLabel.font")); // NOI18N
        catalogSearchLabel.setText(resourceMap.getString("catalogSearchLabel.text")); // NOI18N
        catalogSearchLabel.setName("catalogSearchLabel"); // NOI18N

        catalogSearchField.setName("catalogSearchField"); // NOI18N

        catalogFieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Gênero", "Álbum", "Artista/Banda", "Popularidade", "Preço" }));
        catalogFieldComboBox.setName("catalogFieldComboBox"); // NOI18N

        catalogSearchOKButton.setText(resourceMap.getString("catalogSearchOKButton.text")); // NOI18N
        catalogSearchOKButton.setName("catalogSearchOKButton"); // NOI18N
        catalogSearchOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogSearchOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catalogSearchPanelLayout = new javax.swing.GroupLayout(catalogSearchPanel);
        catalogSearchPanel.setLayout(catalogSearchPanelLayout);
        catalogSearchPanelLayout.setHorizontalGroup(
            catalogSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogSearchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catalogSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catalogFieldComboBox, 0, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(catalogSearchOKButton)
                .addContainerGap())
        );
        catalogSearchPanelLayout.setVerticalGroup(
            catalogSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(catalogSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, catalogSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(catalogFieldComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(catalogSearchOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, catalogSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(catalogSearchLabel)
                        .addComponent(catalogSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout catalogPanelLayout = new javax.swing.GroupLayout(catalogPanel);
        catalogPanel.setLayout(catalogPanelLayout);
        catalogPanelLayout.setHorizontalGroup(
            catalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catalogSearchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        catalogPanelLayout.setVerticalGroup(
            catalogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogPanelLayout.createSequentialGroup()
                .addComponent(catalogSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Catálogo", catalogPanel);

        publicationsPanel.setName("publicationsPanel"); // NOI18N

        publicationsSearchPanel.setName("publicationsSearchPanel"); // NOI18N

        publicationsSearchLabel.setFont(resourceMap.getFont("publicationsSearchLabel.font")); // NOI18N
        publicationsSearchLabel.setText(resourceMap.getString("publicationsSearchLabel.text")); // NOI18N
        publicationsSearchLabel.setName("publicationsSearchLabel"); // NOI18N

        publicationsSearchField.setName("publicationsSearchField"); // NOI18N

        publicationsFieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Gênero", "Álbum", "Artista/Banda", "Popularidade", "Preço" }));
        publicationsFieldComboBox.setName("publicationsFieldComboBox"); // NOI18N

        publicationsSearchOKButton.setText(resourceMap.getString("publicationsSearchOKButton.text")); // NOI18N
        publicationsSearchOKButton.setName("publicationsSearchOKButton"); // NOI18N
        publicationsSearchOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicationsSearchOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout publicationsSearchPanelLayout = new javax.swing.GroupLayout(publicationsSearchPanel);
        publicationsSearchPanel.setLayout(publicationsSearchPanelLayout);
        publicationsSearchPanelLayout.setHorizontalGroup(
            publicationsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicationsSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(publicationsSearchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publicationsSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(publicationsFieldComboBox, 0, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(publicationsSearchOKButton)
                .addContainerGap())
        );
        publicationsSearchPanelLayout.setVerticalGroup(
            publicationsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publicationsSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(publicationsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, publicationsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(publicationsFieldComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(publicationsSearchOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, publicationsSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(publicationsSearchLabel)
                        .addComponent(publicationsSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        publicationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Gênero", "Álbum", "Artista/Banda", "Popularidade", "Preço", "Alterar", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        publicationsTable.setName("publicationsTable"); // NOI18N
        publicationsTable.setRowHeight(25);
        publicationsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(publicationsTable);

        javax.swing.GroupLayout publicationsPanelLayout = new javax.swing.GroupLayout(publicationsPanel);
        publicationsPanel.setLayout(publicationsPanelLayout);
        publicationsPanelLayout.setHorizontalGroup(
            publicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(publicationsSearchPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        publicationsPanelLayout.setVerticalGroup(
            publicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicationsPanelLayout.createSequentialGroup()
                .addComponent(publicationsSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Publicações", publicationsPanel);

        jPanel3.setName("jPanel3"); // NOI18N

        greetingsLabel.setFont(resourceMap.getFont("greetingsLabel.font")); // NOI18N
        greetingsLabel.setText(resourceMap.getString("greetingsLabel.text")); // NOI18N
        greetingsLabel.setName("greetingsLabel"); // NOI18N

        creditsLabel.setFont(resourceMap.getFont("creditsLabel.font")); // NOI18N
        creditsLabel.setForeground(resourceMap.getColor("creditsLabel.foreground")); // NOI18N
        creditsLabel.setText(resourceMap.getString("creditsLabel.text")); // NOI18N
        creditsLabel.setName("creditsLabel"); // NOI18N

        publishButton.setText(resourceMap.getString("publishButton.text")); // NOI18N
        publishButton.setName("publishButton"); // NOI18N
        publishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(publishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publishButton)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(greetingsLabel)
                        .addComponent(creditsLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        systemMenu.setText(resourceMap.getString("systemMenu.text")); // NOI18N
        systemMenu.setName("systemMenu"); // NOI18N

        publishMenuItem.setText(resourceMap.getString("publishMenuItem.text")); // NOI18N
        publishMenuItem.setName("publishMenuItem"); // NOI18N
        publishMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishButtonActionPerformed(evt);
            }
        });
        systemMenu.add(publishMenuItem);

        jSeparator2.setName("jSeparator2"); // NOI18N
        systemMenu.add(jSeparator2);

        changePasswordMenuItem.setText(resourceMap.getString("changePasswordMenuItem.text")); // NOI18N
        changePasswordMenuItem.setName("changePasswordMenuItem"); // NOI18N
        changePasswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordMenuItemActionPerformed(evt);
            }
        });
        systemMenu.add(changePasswordMenuItem);

        jSeparator1.setName("jSeparator1"); // NOI18N
        systemMenu.add(jSeparator1);

        logoutMenuItem.setText(resourceMap.getString("logoutMenuItem.text")); // NOI18N
        logoutMenuItem.setName("logoutMenuItem"); // NOI18N
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        systemMenu.add(logoutMenuItem);

        exitMenuItem.setText(resourceMap.getString("exitMenuItem.text")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        systemMenu.add(exitMenuItem);

        jMenuBar1.add(systemMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        session.logout().showDialog();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void publishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishButtonActionPerformed
        session.showPublishDialog();
    }//GEN-LAST:event_publishButtonActionPerformed

    private void changePasswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordMenuItemActionPerformed
        session.showChangePasswordDialog();
    }//GEN-LAST:event_changePasswordMenuItemActionPerformed

    private void publicationsSearchOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicationsSearchOKButtonActionPerformed
        session.filterPublications(publicationsFieldComboBox.getSelectedItem().toString(), publicationsSearchField.getText());
    }//GEN-LAST:event_publicationsSearchOKButtonActionPerformed

    private void catalogSearchOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogSearchOKButtonActionPerformed
        session.filterCatalog(catalogFieldComboBox.getSelectedItem().toString(), catalogSearchField.getText());
    }//GEN-LAST:event_catalogSearchOKButtonActionPerformed
    
    public javax.swing.JTable getPublicationsTable() {
        return publicationsTable;
    }
    
    public javax.swing.JTable getCatalogTable() {
        return catalogTable;
    }
    
    public javax.swing.JLabel getGreetings() {
        return greetingsLabel;
    }
    
    public javax.swing.JLabel getCreditsLabel() {
        return creditsLabel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox catalogFieldComboBox;
    private javax.swing.JPanel catalogPanel;
    private javax.swing.JTextField catalogSearchField;
    private javax.swing.JLabel catalogSearchLabel;
    private javax.swing.JButton catalogSearchOKButton;
    private javax.swing.JPanel catalogSearchPanel;
    private javax.swing.JTable catalogTable;
    private javax.swing.JMenuItem changePasswordMenuItem;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel greetingsLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JComboBox publicationsFieldComboBox;
    private javax.swing.JPanel publicationsPanel;
    private javax.swing.JTextField publicationsSearchField;
    private javax.swing.JLabel publicationsSearchLabel;
    private javax.swing.JButton publicationsSearchOKButton;
    private javax.swing.JPanel publicationsSearchPanel;
    private javax.swing.JTable publicationsTable;
    private javax.swing.JButton publishButton;
    private javax.swing.JMenuItem publishMenuItem;
    private javax.swing.JMenu systemMenu;
    // End of variables declaration//GEN-END:variables
}
