/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFrame.java
 *
 * Created on 28/03/2012, 20:46:35
 */
package trabalhoes1;

import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author Joao
 */
public class AdministradorFrame extends javax.swing.JFrame {

    /** Creates new form LoginFrame */
    public AdministradorFrame() {
        initComponents();
        definirTabelas();
    }
    
    public void definirTabelas() {
        catalogoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Gênero", "Álbum", "Artista/Banda", "Popularidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        
        produtoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Login", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        
        codigosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        TableColumn column = produtoresTable.getColumnModel().getColumn(3);
        TableButton button = new TableButton("Remover");
        button.addTableButtonListener(new TableButtonListener() {
            @Override
            public void tableButtonClicked(int row, int col) {
                JOptionPane.showMessageDialog(null, "Linha: "+row);
            }
        });
        
        column.setCellRenderer(new TableButton("Remover"));
        column.setCellEditor(button);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        catalogoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catalogoTable = new javax.swing.JTable();
        buscarCatalogoPanel = new javax.swing.JPanel();
        buscarCatalogoLabel = new javax.swing.JLabel();
        buscarCatalogoField = new javax.swing.JTextField();
        atributoCatalogoComboBox = new javax.swing.JComboBox();
        buscarCatalogoOKButton = new javax.swing.JButton();
        listaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        produtoresTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        codigosTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        saudacaoLabel = new javax.swing.JLabel();
        administradorButton = new javax.swing.JButton();
        produtorButton = new javax.swing.JButton();
        codigoButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        SistemaMenu = new javax.swing.JMenu();
        codigoMenuItem = new javax.swing.JMenuItem();
        produtorMenuItem = new javax.swing.JMenuItem();
        administradorMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        senhaMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logoutMenuItem = new javax.swing.JMenuItem();
        sairMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(trabalhoes1.TrabalhoES1App.class).getContext().getResourceMap(AdministradorFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        catalogoPanel.setName("catalogoPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        catalogoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Gênero", "Álbum", "Artista/Banda", "Popularidade", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catalogoTable.setName("catalogoTable"); // NOI18N
        catalogoTable.setRowHeight(25);
        catalogoTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(catalogoTable);
        catalogoTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title0")); // NOI18N
        catalogoTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title1")); // NOI18N
        catalogoTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title2")); // NOI18N
        catalogoTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title3")); // NOI18N
        catalogoTable.getColumnModel().getColumn(4).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title4")); // NOI18N
        catalogoTable.getColumnModel().getColumn(5).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title5")); // NOI18N

        buscarCatalogoPanel.setName("buscarCatalogoPanel"); // NOI18N

        buscarCatalogoLabel.setFont(resourceMap.getFont("buscarCatalogoLabel.font")); // NOI18N
        buscarCatalogoLabel.setText(resourceMap.getString("buscarCatalogoLabel.text")); // NOI18N
        buscarCatalogoLabel.setName("buscarCatalogoLabel"); // NOI18N

        buscarCatalogoField.setFont(resourceMap.getFont("buscarCatalogoField.font")); // NOI18N
        buscarCatalogoField.setText(resourceMap.getString("buscarCatalogoField.text")); // NOI18N
        buscarCatalogoField.setName("buscarCatalogoField"); // NOI18N

        atributoCatalogoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Gênero", "Álbum", "Artista/Banda", "Popularidade", "Preço" }));
        atributoCatalogoComboBox.setName("atributoCatalogoComboBox"); // NOI18N

        buscarCatalogoOKButton.setText(resourceMap.getString("buscarCatalogoOKButton.text")); // NOI18N
        buscarCatalogoOKButton.setName("buscarCatalogoOKButton"); // NOI18N

        javax.swing.GroupLayout buscarCatalogoPanelLayout = new javax.swing.GroupLayout(buscarCatalogoPanel);
        buscarCatalogoPanel.setLayout(buscarCatalogoPanelLayout);
        buscarCatalogoPanelLayout.setHorizontalGroup(
            buscarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarCatalogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarCatalogoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarCatalogoField, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atributoCatalogoComboBox, 0, 126, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarCatalogoOKButton)
                .addContainerGap())
        );
        buscarCatalogoPanelLayout.setVerticalGroup(
            buscarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarCatalogoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buscarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buscarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(atributoCatalogoComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(buscarCatalogoOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, buscarCatalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarCatalogoLabel)
                        .addComponent(buscarCatalogoField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout catalogoPanelLayout = new javax.swing.GroupLayout(catalogoPanel);
        catalogoPanel.setLayout(catalogoPanelLayout);
        catalogoPanelLayout.setHorizontalGroup(
            catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarCatalogoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        catalogoPanelLayout.setVerticalGroup(
            catalogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoPanelLayout.createSequentialGroup()
                .addComponent(buscarCatalogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(resourceMap.getString("catalogoPanel.TabConstraints.tabTitle"), catalogoPanel); // NOI18N

        listaPanel.setName("listaPanel"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        produtoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Login", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtoresTable.setName("produtoresTable"); // NOI18N
        produtoresTable.setRowHeight(25);
        produtoresTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(produtoresTable);
        produtoresTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title0")); // NOI18N
        produtoresTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title1")); // NOI18N
        produtoresTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title2")); // NOI18N
        produtoresTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("listaTable.columnModel.title5")); // NOI18N

        javax.swing.GroupLayout listaPanelLayout = new javax.swing.GroupLayout(listaPanel);
        listaPanel.setLayout(listaPanelLayout);
        listaPanelLayout.setHorizontalGroup(
            listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        listaPanelLayout.setVerticalGroup(
            listaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("listaPanel.TabConstraints.tabTitle"), listaPanel); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        codigosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        codigosTable.setName("codigosTable"); // NOI18N
        codigosTable.setRowHeight(25);
        codigosTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(codigosTable);
        codigosTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title0")); // NOI18N
        codigosTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("catalogoTable.columnModel.title1")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        saudacaoLabel.setFont(resourceMap.getFont("saudacaoLabel.font")); // NOI18N
        saudacaoLabel.setText(resourceMap.getString("saudacaoLabel.text")); // NOI18N
        saudacaoLabel.setName("saudacaoLabel"); // NOI18N

        administradorButton.setText(resourceMap.getString("administradorButton.text")); // NOI18N
        administradorButton.setName("administradorButton"); // NOI18N
        administradorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradorButtonActionPerformed(evt);
            }
        });

        produtorButton.setText(resourceMap.getString("produtorButton.text")); // NOI18N
        produtorButton.setName("produtorButton"); // NOI18N
        produtorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtorButtonActionPerformed(evt);
            }
        });

        codigoButton.setText(resourceMap.getString("codigoButton.text")); // NOI18N
        codigoButton.setName("codigoButton"); // NOI18N
        codigoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saudacaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(codigoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produtorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(administradorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(administradorButton)
                        .addComponent(produtorButton)
                        .addComponent(codigoButton))
                    .addComponent(saudacaoLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        SistemaMenu.setText(resourceMap.getString("SistemaMenu.text")); // NOI18N
        SistemaMenu.setName("SistemaMenu"); // NOI18N

        codigoMenuItem.setText(resourceMap.getString("codigoMenuItem.text")); // NOI18N
        codigoMenuItem.setName("codigoMenuItem"); // NOI18N
        codigoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoButtonActionPerformed(evt);
            }
        });
        SistemaMenu.add(codigoMenuItem);

        produtorMenuItem.setText(resourceMap.getString("produtorMenuItem.text")); // NOI18N
        produtorMenuItem.setName("produtorMenuItem"); // NOI18N
        produtorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtorButtonActionPerformed(evt);
            }
        });
        SistemaMenu.add(produtorMenuItem);

        administradorMenuItem.setText(resourceMap.getString("administradorMenuItem.text")); // NOI18N
        administradorMenuItem.setName("administradorMenuItem"); // NOI18N
        administradorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradorButtonActionPerformed(evt);
            }
        });
        SistemaMenu.add(administradorMenuItem);

        jSeparator2.setName("jSeparator2"); // NOI18N
        SistemaMenu.add(jSeparator2);

        senhaMenuItem.setText(resourceMap.getString("senhaMenuItem.text")); // NOI18N
        senhaMenuItem.setName("senhaMenuItem"); // NOI18N
        senhaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaMenuItemActionPerformed(evt);
            }
        });
        SistemaMenu.add(senhaMenuItem);

        jSeparator1.setName("jSeparator1"); // NOI18N
        SistemaMenu.add(jSeparator1);

        logoutMenuItem.setText(resourceMap.getString("logoutMenuItem.text")); // NOI18N
        logoutMenuItem.setName("logoutMenuItem"); // NOI18N
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        SistemaMenu.add(logoutMenuItem);

        sairMenuItem.setText(resourceMap.getString("sairMenuItem.text")); // NOI18N
        sairMenuItem.setName("sairMenuItem"); // NOI18N
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        SistemaMenu.add(sairMenuItem);

        jMenuBar1.add(SistemaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void administradorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradorButtonActionPerformed
        // TODO add your handling code here:
        CadastroDialog cadastroDialog = new CadastroDialog(this);
        cadastroDialog.setVisible(true);
    }//GEN-LAST:event_administradorButtonActionPerformed

    private void produtorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtorButtonActionPerformed
        // TODO add your handling code here:
        CadastroDialog cadastroDialog = new CadastroDialog(this);
        cadastroDialog.setVisible(true);
    }//GEN-LAST:event_produtorButtonActionPerformed

    private void codigoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoButtonActionPerformed
        // TODO add your handling code here:
        CadastrarCodigoDialog cadastrarCodigoDialog = new CadastrarCodigoDialog(this);
        cadastrarCodigoDialog.setVisible(true);
    }//GEN-LAST:event_codigoButtonActionPerformed

    private void senhaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaMenuItemActionPerformed
        // TODO add your handling code here:
        AlterarSenhaDialog alterarSenhaDialog = new AlterarSenhaDialog(this);
        alterarSenhaDialog.setVisible(true);
    }//GEN-LAST:event_senhaMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdministradorFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SistemaMenu;
    private javax.swing.JButton administradorButton;
    private javax.swing.JMenuItem administradorMenuItem;
    private javax.swing.JComboBox atributoCatalogoComboBox;
    private javax.swing.JTextField buscarCatalogoField;
    private javax.swing.JLabel buscarCatalogoLabel;
    private javax.swing.JButton buscarCatalogoOKButton;
    private javax.swing.JPanel buscarCatalogoPanel;
    private javax.swing.JPanel catalogoPanel;
    private javax.swing.JTable catalogoTable;
    private javax.swing.JButton codigoButton;
    private javax.swing.JMenuItem codigoMenuItem;
    private javax.swing.JTable codigosTable;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel listaPanel;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JButton produtorButton;
    private javax.swing.JMenuItem produtorMenuItem;
    private javax.swing.JTable produtoresTable;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JLabel saudacaoLabel;
    private javax.swing.JMenuItem senhaMenuItem;
    // End of variables declaration//GEN-END:variables
}
